name: Trigger Webhook

on:
  push:
    branches:
      - main

jobs:
  trigger-webhook:
    runs-on: ubuntu-latest
    steps:
    - name: Run curl to trigger webhook
      run: curl -X POST -H "Content-Type: application/json" -d '{"key": "value"}' ${{ secrets.WEBHOOK }}
      env:
        WEBHOOK: ${{ secrets.WEBHOOK }}
