name: Webhook Trigger

on:
  push:
    branches:
      - main

jobs:
  trigger_webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Webhook
        env:
          WEBHOOK_SECRET: ${{ secrets.WEBHOOK }}
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{"key": "value"}' $WEBHOOK_SECRET
